// ============================================================
// LESSONS V2 — TypeScript types matching content/lessons/*.yaml
// Source data is generated by scripts/compile-lessons.mjs into
// lessonsV2.data.json and imported here.
// ============================================================

import data from "./lessonsV2.data.json";

export type PageMode = "see" | "hear" | "play";

export type InteractionType =
  | "sequence"
  | "rhythm"
  | "song"
  | "drill"
  | "rhythm_race"
  | "drag";

export interface InteractionSequence {
  type: "sequence";
  keys: string[]; // e.g. ["C4","D4","E4"]
}

export interface InteractionRhythm {
  type: "rhythm";
  sequence: (string | string[])[];
  durations?: string[];
  tempo?: number;
}

export interface InteractionSong {
  type: "song";
  sequence: (string | string[])[];
  guides?: boolean;
  tempo?: number;
}

export interface InteractionDrill {
  type: "drill";
  /** Either an integer count, or a list of per-round {question, options}. */
  rounds?: number | { question: string; options: string[] }[];
  question?: string;
  options?: string[];
}

/**
 * Race-the-metronome — repeated short rhythm pattern that speeds up each
 * successful round. Visual: speedometer-style tempo dial. Wrong note
 * doesn't fail; the round just resets at the current tempo.
 */
export interface InteractionRhythmRace {
  type: "rhythm_race";
  /** Notes (or chord arrays) the student plays each round. */
  sequence: (string | string[])[];
  /** Beat values per item, same convention as `rhythm`. */
  durations?: string[];
  /** Starting BPM. Default 60. */
  start_tempo?: number;
  /** BPM increment per successful round. Default 5. */
  step?: number;
  /** Number of rounds before the page completes. Default 6. */
  rounds?: number;
}

/**
 * Drag-and-drop interaction. v1 supports the most common pedagogical use
 * — drag a note onto a staff line/space. Other kinds (finger numbers
 * onto keys, durations onto notes) can be added later by extending the
 * item/target unions.
 */
export interface InteractionDrag {
  type: "drag";
  item: DragItem;
  target: DragTarget;
  /** Optional prompt above the drag area. */
  prompt?: string;
}

export type DragItem =
  | { kind: "note"; pitch: string }   // a draggable note head, labelled with pitch letter
  | { kind: "finger"; number: 1 | 2 | 3 | 4 | 5 }
  | { kind: "duration"; value: "quarter" | "half" | "whole" };

export type DragTarget =
  | { kind: "staff_line"; line: 1 | 2 | 3 | 4 | 5; clef?: "treble" | "bass" }
  | { kind: "staff_space"; space: 1 | 2 | 3 | 4; clef?: "treble" | "bass" }
  | { kind: "staff_pitch"; pitch: string; clef?: "treble" | "bass" }
  | { kind: "key"; midi: number };

export type Interaction =
  | InteractionSequence
  | InteractionRhythm
  | InteractionSong
  | InteractionDrill
  | InteractionRhythmRace
  | InteractionDrag;

export interface LessonPage {
  id: number | string; // usually int, occasionally "1a"
  mode: PageMode;
  type: string;
  figure?: string;
  cleffy?: string;
  completion_cleffy?: string;
  followup_cleffy?: string;
  audio?: Record<string, string>; // e.g. { A: "...", B: "..." }
  interaction?: Interaction;
  /**
   * Map MIDI number → CSS color. Baked in by scripts/compile-lessons.mjs
   * from figure/cleffy text. When rendering the bottom piano we merge this
   * with any live state (press feedback, next-expected pulse).
   */
  highlights?: Record<string | number, string>;
  /**
   * "Did you notice?" pop-up. Surfaces a one-line meta observation in a
   * Cleffy bubble after this page completes, before the next page
   * renders. Tap to dismiss. Optional — most pages won't have one.
   * Format: 6-15 words, single sentence, no period required.
   */
  notice?: string;
}

export interface MasteryQuestion {
  figure?: string;
  audio?: string;
  prompt: string;
  options?: string[];
  correct?: number;
  accept?: string;
}

export interface MasterySection {
  pass_threshold: number;
  questions: MasteryQuestion[];
}

export interface MasteryCheck {
  sections: {
    see?: MasterySection;
    hear?: MasterySection;
    play?: MasterySection;
  };
}

export interface Remediation {
  id: string; // e.g. "25.5"
  title: string;
  pages: number;
  opening_cleffy: string;
}

export interface Completion {
  cleffy: string;
  xp: number;
  unlocks?: number;
  tier_complete?: number;
}

export interface Piece {
  title: string;
  composer?: string;
  key_center?: string;
  time_signature?: string;
  difficulty?: string;
  [key: string]: unknown;
}

export interface PracticeThisWeek {
  real_piano?: string[];
  virtual_only?: string[];
  estimated_time?: string;
}

export interface LessonV2 {
  id: number;
  tier: string;
  act: number;
  title: string;
  subtitle?: string;
  goal: string;
  prereqs?: number[];
  method_focus?: string;
  time_estimate_min?: number;
  piece_context?: string;
  metaphor?: string;
  vibe?: string[];
  is_act_boss?: boolean;
  is_tier_boss?: boolean;
  is_mid_boss?: boolean;
  is_graduation?: boolean;
  piece?: Piece;
  pages: LessonPage[];
  practice_this_week?: PracticeThisWeek;
  mastery_check?: MasteryCheck;
  remediation?: Remediation;
  completion: Completion;
}

export const lessonsV2: LessonV2[] = data as LessonV2[];

export function findLessonV2(id: number): LessonV2 | undefined {
  return lessonsV2.find((l) => l.id === id);
}

/**
 * Map lesson+page to the pre-generated audio file path.
 *
 * Audio is served from the `NEXT_PUBLIC_AUDIO_BASE_URL` origin (S3 bucket).
 * The fallback is the public S3 URL so production builds work without env
 * config; local dev can override via `.env.local` to point at a local mirror.
 */
const DEFAULT_AUDIO_BASE = "https://sonata-audio.s3.eu-west-1.amazonaws.com/audio";

export function pageAudioSrc(lessonId: number, pageId: number | string): string {
  const lidSlug = String(lessonId).padStart(3, "0");
  const pidSlug = String(pageId).padStart(2, "0");
  const base = process.env.NEXT_PUBLIC_AUDIO_BASE_URL || DEFAULT_AUDIO_BASE;
  return `${base.replace(/\/$/, "")}/lesson-${lidSlug}/page-${pidSlug}.mp3`;
}

/** Does this page have Cleffy-spoken narration? (Not every page does.) */
export function pageHasNarration(page: LessonPage): boolean {
  return !!(page.cleffy || page.completion_cleffy || page.followup_cleffy);
}
